[build]
  command="ng build"
  functions = "netlify/functions"
  publish="dist/straweb-portfolio/browser"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
  package = "netlify-plugin-cypress"

  [plugins.inputs.postBuild]
    enable = true

  [plugins.inputs]
      # Optional: Configure inputs for the plugin
      # For example, to specify a base URL for Cypress to test against
    cypress_base_url = "http://localhost:4200"
    enable = false
