[build]
  command="ng build"
  functions = "netlify/functions"
  publish="dist/straweb-portfolio/browser"

  [build.environment]
    # cache Cypress binary in local "node_modules" folder
    # so Netlify caches it
    CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"
    # set TERM variable for terminal output
    TERM = "xterm"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
  package = "netlify-plugin-cypress"

  [plugins.inputs.postBuild]
    enable = true

  [plugins.inputs]
      # Optional: Configure inputs for the plugin
      # For example, to specify a base URL for Cypress to test against
    #cypress_base_url = "http://localhost:4200"
    enable = false
